CREATE PROCEDURE [dbo].[spd_tblPOMaster_Delete]
	@POID INT
AS
BEGIN
	BEGIN TRY		
		BEGIN TRANSACTION			
		
		-- DELETE ALL PO DETAILS
		DELETE FROM [dbo].[tblPODetails] 
		WHERE [POID] = @POID		

		-- DELETE PO MASTER
		DELETE FROM [dbo].[tblPOMaster] 
		WHERE [POID] = @POID					 

		COMMIT TRANSACTION
	END TRY
	BEGIN CATCH		
		
		ROLLBACK TRANSACTION		

	END CATCH 
END